### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Endless-Rage-ok** [birjolaxew/skribbl.io-streamer-mode#2]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
Failed to get elements from DOM [object Object]
Uncaught Error: Couldn't find needed elements
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
Uncaught ReferenceError: domWatcher is not defined

**Comment by birjj** [comment]
As mentioned in the README:

> **Warning**  
> This extension is not updated for the newest skribbl.io update, and is currently non-functional.

See also #1. While I welcome PRs to fix it up for the new DOM structure, I don't plan on implementing it myself.
